SEVERITY = {"critical", "high", "medium", "low"}
FAIL_LEVELS = {"none": 5, "critical": 1, "high": 2, "medium": 3, "low": 4}

RULES = [
    ("secret-aws-access-key", "critical", "secret", "AWS access key", r"AKIA[0-9A-Z]{16}"),
    ("secret-github-token", "critical", "secret", "GitHub token", r"gh[pousr]_[A-Za-z0-9_]{20,}"),
    ("secret-openai-key", "critical", "secret", "OpenAI API key", r"sk-[A-Za-z0-9]{20,}"),
    ("secret-anthropic-key", "critical", "secret", "Anthropic API key", r"sk-ant-[A-Za-z0-9_-]{20,}"),
    ("secret-slack-token", "critical", "secret", "Slack token", r"xox[baprs]-[A-Za-z0-9-]{10,}"),
    ("secret-high-entropy", "high", "secret", "High entropy secret candidate", r"(?i)\b(api[_-]?key|secret|token|password|passwd|pwd|private[_-]?key|access[_-]?key)\b\s*[:=]\s*['\"]?([^'\"\s,}]{17,})"),
    ("secret-generic", "high", "secret", "Generic secret assignment", r"(?i)\b(api[_-]?key|secret|token|password|passwd|pwd)\b\s*[:=]\s*['\"]?[^'\"\s]+"),
    ("prompt-ignore-instructions", "high", "prompt-injection", "Instruction override", r"(?i)ignore (all )?(previous|prior) instructions|disregard (all )?(previous|prior) instructions|system prompt|developer instructions|reveal your instructions"),
    ("prompt-jailbreak", "high", "prompt-injection", "Jailbreak pattern", r"(?i)jailbreak|bypass safety|bypass restrictions|do not follow|override your rules"),
    ("prompt-exfiltration", "critical", "prompt-injection", "Prompt injection with exfiltration", r"(?i)exfiltrate|send .* (token|secret|api key|credentials)|upload .* (token|secret|api key|credentials)|post .* (token|secret|api key|credentials)"),
    ("exfil-webhook", "critical", "data-exfiltration", "Webhook exfiltration", r"(?i)(discord|slack|webhook\.site|requestbin|ngrok).* (token|secret|api key|credentials|env)|send .* to https?://|post .* to https?://"),
    ("shell-curl-pipe", "critical", "dangerous-command", "Curl pipe to shell", r"(?i)curl\b[^\n|;]*\|\s*(sh|bash)|wget\b[^\n|;]*\|\s*(sh|bash)"),
    ("shell-rm-rf", "critical", "dangerous-command", "Recursive delete command", r"(?i)\brm\s+(-[rf]+\s+)*(/|\*|~|\.\.|[A-Za-z]:\\)|rmdir\s+/s\s+/q"),
    ("shell-sudo", "high", "dangerous-command", "Privileged command", r"(?i)\bsudo\b|\brun as administrator\b|Invoke-Command\s+-Credential"),
    ("shell-encode", "high", "dangerous-command", "Encoded PowerShell", r"(?i)powershell\s+(-enc|-encodedcommand)|cmd\s+/c"),
    ("shell-network-fetch", "medium", "dangerous-command", "Remote script fetch", r"(?i)\b(curl|wget|Invoke-WebRequest|IEX)\b[^\n]*(https?://|githubusercontent\.com)"),
    ("db-destructive", "critical", "dangerous-command", "Destructive database command", r"(?i)\b(drop|truncate|delete from)\b\s+(table|database)|\bdrop\s+database\b"),
    ("file-sensitive", "critical", "sensitive-file", "Sensitive file access", r"(?i)(\.ssh|id_rsa|id_dsa|\.env|known_hosts|credentials|kubeconfig|htpasswd)"),
    ("file-broad-read", "high", "sensitive-file", "Broad filesystem read", r"(?i)(read_file|cat|Get-Content|type)\s+['\"]?(/|C:\\|\*|\.env|/etc|/var)"),
    ("mcp-shell-tool", "high", "mcp-permissions", "MCP shell tool risk", r"(?i)mcp.* (shell|exec|command)|tool.* (shell|exec|command)"),
    ("mcp-broad-permission", "high", "mcp-permissions", "Broad MCP permission", r"(?i)permissions?\s*[:=]\s*['\"]?\*['\"]?|allow\s+all|read\s+all|write\s+all"),
    ("supply-eval", "high", "supply-chain", "Dynamic code execution", r"(?i)\beval\s*\(|Function\s*\(.*\)|new\s+Function\s*\("),
    ("supply-child-process", "high", "supply-chain", "Child process execution", r"(?i)child_process\.exec|subprocess\.(call|run|Popen)|os\.system\s*\("),
    ("supply-install", "medium", "supply-chain", "Dependency install command", r"(?i)\b(npm|yarn|pnpm|pip|pip3|cargo)\s+install\b"),
    ("cve-reference", "medium", "vulnerability", "CVE reference", r"CVE-\d{4}-\d{4,7}"),
    ("exploit-reference", "high", "vulnerability", "Exploit reference", r"(?i)\b(exploit|poc|proof of concept|lpe|privilege escalation)\b"),
    ("agent-tool-permissions", "medium", "agent-security", "Agent tool permission block", r"(?i)\b(tools|permissions|allowed_tools|allowedTools|function_calling)\b"),
]

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    "dist",
    "build",
    ".next",
    ".turbo",
    "target",
    "coverage",
    ".pytest_cache",
}

TEXT_EXTENSIONS = {
    "",
    ".py",
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".md",
    ".txt",
    ".env",
    ".sh",
    ".bash",
    ".ps1",
    ".psm1",
    ".cmd",
    ".bat",
    ".go",
    ".rs",
    ".rb",
    ".java",
    ".cs",
    ".csproj",
    ".cshtml",
    ".html",
    ".vue",
    ".svelte",
    ".sql",
    ".xml",
    ".ini",
    ".cfg",
    ".conf",
    ".dockerfile",
    "dockerfile",
}
